INFO: Starting training:
        Image:           data/1_input_scratch/JPEGImages
        Label:           data/1_input_scratch/SegmentationClass
        Checkpoints:     data/14_output_checkpoint_unet
        Epochs:          5
        Batch size:      1
        Learning rate:   1e-05
        Training size:   450
        Validation size: 50
        Checkpoints:     True
        Device:          cuda
        Images scaling:  0.5
        Mixed Precision: False

Epoch 1/5:   0%|          | 0/450 [00:34<?, ?img/s]
Traceback (most recent call last):
  File "D:/Dropbox/PhD/python/GAN_SCRATCH_1/unet/train.py", line 196, in <module>
    train_net(net=net,
  File "D:/Dropbox/PhD/python/GAN_SCRATCH_1/unet/train.py", line 101, in train_net
    + dice_loss(F.softmax(masks_pred, dim=1).float(),
  File "C:\Users\anindita\anaconda3\envs\envTorch1\lib\site-packages\torch\nn\functional.py", line 1818, in softmax
    ret = input.softmax(dim)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.